/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: paliacci (https://sketchfab.com/paliacci)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free---skybox-blue-desert-9597e9a5327849f79e485fe8bbe839f9
Title: Free_-_skybox_blue_desert
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import skyScene from "../assets/3D/sky.glb";

const Sky = (props) => {
  const { nodes, materials } = useGLTF(skyScene);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={112}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials["Scene_-_Root"]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/free_-_skybox_blue_desert (1).glb");

export default Sky;
