/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-blue-desert-fd952e60be9746e0872840e89fbf7370
Title: FREE - SkyBox Blue Desert
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import skyScene from "../assets/3D/sky.glb";

const Sky = (props) => {
  const { nodes, materials } = useGLTF(skyScene);
  return (
    <group {...props} dispose={null} position={[0, 0, -1000]} scale={[1, 1, 1]}>
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere__0.geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/free_-_skybox_blue_desert.glb");

export default Sky;
